export const MATCH_DEFAULT_OSCILLATORS = 10;
export const MATCH_DEFAULT_ITERATIONS = 100;
export const MATCH_DEFAULT_STEP_GROWTH_ADD = 0.0007;
export const MATCH_DEFAULT_STEP_DECAY_FACTOR = 0.97;
export const MATCH_DEFAULT_STAGE_DURATION_MULTIPLIER = 2;
